name: "🚀 Github Release"
on:
  push:
    tags:
      - '[0-9]+.[0-9].+[0-9]+'
      - '[0-9]+.[0-9].+[0-9]+-rc.[0-9]+'

jobs:
  release-matrix:
    strategy:
      matrix:
        platform: [web, android, ios]
    name: Github Release ${{ matrix.platform }}
    runs-on: ${{ matrix.platform == 'ios' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - name: 🚚 Get code
        uses: actions/checkout@v2
      - name: 🚚 Get Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: 🚚 Get Ruby Deps
        run: |
          bundle install
      - if: matrix.platform == 'android'
        name: Setup java
        uses: actions/setup-java@v1
        with:
            distribution: 'zulu'
            java-version: '11'
      - name: 🚚 Get node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: 🚚 Generate Web and Changelog
        if: matrix.platform == 'web'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --unshallow --tags &&
          npm -g install semver &&
          pip install gitchangelog pystache &&
          bundle exec fastlane ${{ matrix.platform }} publish_github draft:true changelog:true
      - name: 🚚 Create Github release
        if: matrix.platform != 'web'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ## ios build
          MATCH_PASSWORD: ${{ secrets.IOS_MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          API_KEY: ${{ secrets.IOS_API_KEY }}
          ## android build
          KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        run: |
          bundle exec fastlane ${{ matrix.platform }} publish_github draft:true
