name: "🚀 Github Release"
on:
  push:
    tags:
      - '[0-9]+.[0-9].+[0-9]+'
      - '[0-9]+.[0-9].+[0-9]+-rc.[0-9]+'

jobs:
  release-matrix:
    strategy:
      matrix:
        platform: [web, android]
    name: Github Release ${{ matrix.platform }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get code
        uses: actions/checkout@v2
      - name: 🚚 Get Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: 🚚 Get Ruby Deps
        run: |
          bundle install
      - if: matrix.platform == 'android'
        name: Setup java
        uses: actions/setup-java@v1
        with:
            distribution: 'zulu'
            java-version: '11'
      - name: 🚚 Get node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: 🚚 Create assets and github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        run: |
          git fetch --unshallow --tags &&
          npm -g install semver &&
          pip install gitchangelog pystache &&
          bundle exec fastlane ${{ matrix.platform }} publish_github draft:true

